export const VEGETABLE_OPTIONS = [
  'CRT (Carrot)',
  'BRT (Beetroot)',
  'Caps (Capsicum)',
  'CB (Cabbage)',
  'CF (Cauliflower)',
  'Chama (Taro Root)',
  'BM (Bajji Mirchi)',
  'ML (Mullangi)',
  'Beera (Ridge Gourd)',
  'BNS (Green Beans)',
  'Kakara (Bitter Gourd)',
  'AA Kakara (Teasel Gourd)',
  'Dhonda (Ivy Gourd)',
  'Keera (Cucumber)',
  'Benda (Okra)',
  'Sora (Bottle Gourd)',
  'Mirchi (Green Chilli)',
  'Dosa (Yellow Cucumber)',
  'Munaga (Drumstick)',
  'Ulli (Onion)',
  'Gummadi (Pumpkin)',
  'Coolie',
  'Sweetcorn',
];
